### ISSUE TITLE
Calculate value in template

### ISSUE THREAD

**Issue by khushboobansal1910** [SelectTransform/st.js#21]
Hi,

I have a simple doubt. I am trying to do transformation.

Consider that my input data is like below :
var data = {
"a":{
"price": 10
},
"b":{
"profit":3
}
};

and the template is :
 var temp = {
"sale": "{{a.price}}+{{b.profit}}"
};

output what i recieved :
{
  "sale": "10+3"
}

but I expect the output to be:
{
  "sale": 13
}

Also, I tried using parseInt in template but the it gave me null as result.

Is there any way to achieve the expected output?

**Comment by gliechtenstein** [comment]
Try

```
var temp = {
  "sale": "{{a.price + b.profit}}"
}
```

All results of template evaluation are strings, therefore it's by design that you end up with the `"10 + 3"` string when you separate them out into two separate template expressions.

**Comment by khushboobansal1910** [comment]
Thanks for the reply. It worked for me but if my data gets twisted it shows me a problem again.

If my data now is
 var data = {
"a":{
"price": "10"
},
"b":{
"profit":"3"
}
};

then it concatenates the two string and give me the result as

{
"sale": 103
}

but still I want the result to be

{
"sale": 13
}

Can you please provide me a solution for this

**Comment by khushboobansal1910** [comment]
Gentle Reminder!

**Comment by mihir83in** [comment]
`var temp = {
  "sale": "{{(a.price + b.profit)}}"
}`

If that doesn't work try 
`var temp = {
  "sale": "{{Number(a.price) + Number(b.profit)}}"
}`

**Comment by khushboobansal1910** [comment]
Thanks! It worked.
