### ISSUE TITLE
Future project

### ISSUE THREAD

**Issue by zababurinsv** [SelectTransform/st.js#36]
Good afternoon.

I want to use st.js.
Please tell me, is the library developing now or is it a project that will soon stop developing?
I ask because there are no 2 reptiles updates already.

Site http://www.st-js.org/ not work.

**Comment by xiddig** [comment]
> Good afternoon.
> 
> I want to use st.js.
> Please tell me, is the library developing now or is it a project that will soon stop developing?
> I ask because there are no 2 reptiles updates already.

Hello, the project has been frozen for 2 years, if you are interested, I have been correcting bugs for months and continuing the project for a long time, in a parallel repository, where I maintain it and keep adding functionalities to this incredible library.

https://xiddig.github.io/site/

**Comment by zababurinsv** [comment]
Thanks.

Thank. It will be very helpful.
I did not understand everything in this library.
But I gathered it from myself a little differently.
I made all the code asynchronous and tried to divide it into modules.
