### ISSUE TITLE
FUTURE THE PROJECT, YES IS ACTIVE!!!!

### ISSUE THREAD

**Issue by mpanichella** [SelectTransform/st.js#39]
sadly the selecttransform project is no longer maintained. Currently I have been using the library heavily, and I started adding new functionality and changes to it. It is for this reason that I decided to maintain and continue to evolve the library as it is very powerful.

For this reason, the project will continue to be active, evolving, and correcting bugs through the repository.

I will continue to work hard to make this library grow and be much better than it is today. I hope that you help me to continue growing.

https://github.com/xiddig

**`npm install @xiddig/transform`**

`const XT = require("@xiddig/transform");`

`const parsed = XT.select({ "items": [1,2,3,4] })`
`                .transformWith({`
`                  "{{#each items}}": {`
`                    "type": "label", "text": "{{this}}"`
`                  }`
`                })`
`                .root();`

In turn, the library is active and updated at npmjs.com

**Comment by JakubMifek** [comment]
Hi @mpanichella, I myself cloned the repo and rewritten it quite a bit and extended it's features several months ago. You can find it here: https://github.com/JakubMifek/SelectTransform/ 

It would be gr8 if we maybe combined our forces :)
