### ISSUE TITLE
Consider not extending native prototypes and objects?

### ISSUE THREAD

**Issue by JayAndCatchFire** [SelectTransform/st.js#6]
This may be related to https://github.com/SelectTransform/st.js/issues/1, but perhaps consider not extending native APIs and prototypes?  [Some people](https://stackoverflow.com/questions/14034180/why-is-extending-native-objects-a-bad-practice) get really mad about that sort of thing.  It makes it harder to use as part of a project that relies on libraries that provide exports.  As larger projects move to Webpack (and its kin), this may be a barrier to adoption.

Currently, this library adds `select`, `inject`, and `transform` to the `JSON` object.  It also adds `$root` to `String`, `Number`, `Function`, `Array`, and `Boolean` native prototypes.

**Comment by caesay** [comment]
I think this is super important for any kind of wide adoption. I really like how this library is looking and this is one of the few reasons I can't give it a try. (It's a code standards thing). A standard export/import directive would be best. Even an object on the global scope would be better, like `global.stjs.etc(`

**Comment by gliechtenstein** [comment]
Great points. I think there are two issues here:

## 1. don't add `$root` to prototypes

`$root` override was necessary for handling root context while looping https://github.com/SelectTransform/site/blob/gh-pages/src/markdown/transform/features.md#7-root  If you have an idea to do this without using the `$root` variable, please feel free to share or send a PR.

That said, I think we could fix this by cleaning it up before returning the object. Maybe something like:

```
delete Number.prototype.$root
```

That way we're not left with dangling `$root` attributes for all the prototypes. How does that sound?


## 2. don't override `JSON`

But I agree with your sentiment about the override, so this will probably happen. This one would be technically simple--just need to stop doing it.

The library already exposes the variable `ST` so you can do:

```
ST.select(template).transform(data)
ST.select(data).transformWith(template)
```

So all we need to do is suppress the JSON override. I haven't decided whether to provide an option to opt into (or opt out from) JSON override, or to completely get rid of it.  Just need to decide on which direction to go.

Please share if anyone has any further thoughts.

**Comment by caesay** [comment]
@gliechtenstein If someone wants to have the JSON override, it would be as simple as adding this in their own code.. `JSON.select = ST.select`. For that reason, I think it would be best to leave it out completely.

Regarding `$root`, I see the usefulness as a feature but I don't understand why it needs to extend the prototype (as opposed to just storing $root in the scope while doing the transform). I'll have a look at the code and come back to you.

**Comment by gliechtenstein** [comment]
This issue has been addressed with https://github.com/SelectTransform/st.js/commit/d05ae20b336cc0f0d786b2808ad23b0f54036ff1 and also reflected on the documentation https://selecttransform.github.io/site/

Please feel free to reopen if you find anything I missed, thanks
